In [1]:
# initial library import
import pandas as pd
import numpy as np

In [2]:
# view the data
df = pd.read_csv('pos_train.csv')
df.head()

Nose_x    Nose_y    Neck_x    Neck_y  Rshoulder_x  Rshoulder_y  Relbow_x  \
0  0.484251  0.432114  0.464759  0.890685     0.191389     0.869759 -0.003906   
1  0.601518  0.448081  0.578051  0.942834     0.296927     0.926980 -0.003906   
2  0.538944  0.432346  0.558527  0.937304     0.277261     0.926996 -0.003906   
3  0.562560  0.474093  0.531152  0.875009     0.230478     0.854189 -0.003906   
4  0.503938  0.489706  0.484372  0.880143     0.210912     0.854289 -0.003906   

   Relbow_y  Rwrist_x  Rwrist_y  ...  frame_w  frame_y  Posture  Nose_Neck_A  \
0 -0.005208 -0.003906 -0.005208  ...    640.0    480.0  correct    92.433940   
1 -0.005208 -0.003906 -0.005208  ...    640.0    480.0  correct    92.715533   
2 -0.005208 -0.003906 -0.005208  ...    640.0    480.0  correct    87.779122   
3 -0.005208 -0.003906 -0.005208  ...    640.0    480.0  correct    94.479392   
4 -0.005208 -0.003906 -0.005208  ...    640.0    480.0  correct    92.868759   

   Rshoulder_Neck_A  Lshoulder_Neck_A  Rshoulder_Relbow_A  Lshoulder_Lelbow_A  \
0          4.377248        179.985251                90.0                90.0   
1          3.227724        179.953771                90.0                90.0   
2          2.098752        176.926767                90.0                90.0   
3          3.961013        179.007135                90.0                90.0   
4          5.400991       -179.986234                90.0                90.0   

   Relbow_Rwrist_A  Lelbow_Lwrist_A  
0             90.0             90.0  
1             90.0             90.0  
2             90.0             90.0  
3             90.0             90.0  
4             90.0             90.0  

[5 rows x 30 columns]

In [3]:
# import ml library
from sklearn.ensemble import RandomForestClassifier

In [18]:
# instantiate model
classifier = RandomForestClassifier(n_estimators=55, oob_score=True,\
                                    bootstrap=True)

In [19]:
# joints list
joint_angles = ['Nose_Neck_A','Rshoulder_Neck_A','Lshoulder_Neck_A','Rshoulder_Relbow_A',\
               'Lshoulder_Lelbow_A',]
joint_angles += ['Relbow_Rwrist_A','Lelbow_Lwrist_A']
joint_angles=[]

In [33]:
# joint_angles

In [21]:
# df['Posture'],
# df.drop('Posture',axis=1)
# df.shape
x_train = df.drop(['Posture','frame_w','frame_y']+joint_angles,axis=1)
y_train = df['Posture']

In [22]:
# train model
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=55,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [23]:
# prediction on data (of trained model)
Y_pred = classifier.predict(x_train)

In [24]:
Y_pred = Y_pred.reshape(len(Y_pred), 1)

In [25]:
Y_pred

array([['correct'],
       ['correct'],
       ['correct'],
       ...,
       ['Tilted right'],
       ['Tilted right'],
       ['Tilted right']], dtype=object)

In [26]:
# import test dataset
df_test = pd.read_csv('pos_test.csv')
df_test.head()

Nose_x    Nose_y    Neck_x    Neck_y  Rshoulder_x  Rshoulder_y  Relbow_x  \
0  0.593756  0.432276  0.593667  0.911386     0.316435     0.906274 -0.003906   
1  0.582019  0.416806  0.589876  0.901146     0.308640     0.890578 -0.003906   
2  0.519618  0.453126  0.550721  0.942650     0.281320     0.942605 -0.003906   
3  0.574278  0.447890  0.585919  0.942587     0.300875     0.921852 -0.003906   
4  0.593668  0.432235  0.582157  0.895967     0.316464     0.901070 -0.003906   

   Relbow_y  Rwrist_x  Rwrist_y  ...  frame_w  frame_y  Posture  Nose_Neck_A  \
0 -0.005208 -0.003906 -0.005208  ...      640      480  correct    90.010735   
1 -0.005208 -0.003906 -0.005208  ...      640      480  correct    89.070595   
2 -0.005208 -0.003906 -0.005208  ...      640      480  correct    86.364470   
3 -0.005208 -0.003906 -0.005208  ...      640      480  correct    88.651994   
4 -0.005208 -0.003906 -0.005208  ...      640      480  correct    91.421861   

   Rshoulder_Neck_A  Lshoulder_Neck_A  Rshoulder_Relbow_A  Lshoulder_Lelbow_A  \
0          1.056407       -177.815548                90.0                90.0   
1          2.152096       -176.912301                90.0                90.0   
2          0.009698        175.800236                90.0                90.0   
3          4.160624       -179.980265                90.0                90.0   
4         -1.100255       -176.792651                90.0                90.0   

   Relbow_Rwrist_A  Lelbow_Lwrist_A  
0             90.0             90.0  
1             90.0             90.0  
2             90.0             90.0  
3             90.0             90.0  
4             90.0             90.0  

[5 rows x 30 columns]

In [27]:
x_test = df_test.drop(['Posture','frame_w','frame_y']+joint_angles, axis=1)
y_test = df_test['Posture']

In [28]:
y_pred = classifier.predict(x_test)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Train accuracy", accuracy_score(y_train, Y_pred))
print("Test accuracy", accuracy_score(y_test, y_pred))
# print(classifier.oob_score_)

[[ 168    0    0    0    0    0]
 [   0 1428    0    0    1    0]
 [   0    0 1543    0    0    0]
 [   0    0    0 1133    0    0]
 [   5   38    0   53 1005    0]
 [  27    0    0   45    3 1068]]
Train accuracy 1.0
Test accuracy 0.9736074881080251


In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


               precision    recall  f1-score   support

        Shrug       0.84      1.00      0.91       168
  Tilted left       0.97      1.00      0.99      1429
 Tilted right       1.00      1.00      1.00      1543
      correct       0.92      1.00      0.96      1133
lean backward       1.00      0.91      0.95      1101
 lean forward       1.00      0.93      0.97      1143

     accuracy                           0.97      6517
    macro avg       0.96      0.97      0.96      6517
 weighted avg       0.98      0.97      0.97      6517



In [31]:
import pickle
with open('pose_model.pkl','wb') as file:
    pickle.dump(classifier, file)

In [34]:
with open('pose_model.pkl', 'rb') as file:
    classifier = pickle.load(file)
    
x = x_train.values[0].reshape(1,-1)
    
%time y = classifier.predict(x)

CPU times: user 3.3 ms, sys: 0 ns, total: 3.3 ms
Wall time: 3.2 ms


In [35]:
x.shape

(1, 27)

In [36]:
print(y[0])

correct
